set {
  # @Mod key
  $mod Mod4

  # @Apps
  $term kitty
  $menu fuzzel
  $browser zen-browser
  $file nautilus
  $music kitty --app-id jukebox -o window_padding_width=0 rmpc
  $clipboard-history bash $HOME/.config/sway/scripts/clipboard-history.sh
  
  # @Scripts
  $lock bash $HOME/.config/sway/scripts/lock.sh
  $logout bash $HOME/.config/sway/scripts/wlogout.sh
  $volume bash $HOME/.config/sway/scripts/volume.sh
  $media bash $HOME/.config/sway/scripts/media.sh
  $brightness bash $HOME/.config/sway/scripts/brightness.sh
  $screenshot bash $HOME/.config/sway/scripts/screenshot.sh
  $autostart bash $HOME/.config/sway/scripts/autostart.sh

  # @Home row direction
  $left h
  $down j
  $up k
  $right l

  # @Colors
  $bg-color            #292522
  $text-color          #E8D5B0
  $inactive-text-color #867462
  $urgent-bg-color     #C0392B
  $accent-color        #E08A3C
  $overlay-bg-color    #403A36
}
