# global music library directory
music_directory "~/Music/library"

# only available in localhost
bind_to_address "127.0.0.1"

# MPD related files in "~/.mpd"

# MPD internal playlists directory
playlist_directory "~/.mpd/playlists"

# MPD db
db_file "~/.mpd/database"
auto_update "yes" # automatically updates db

# logs
log_file "~/.mpd/log"

# persistent PID of MPD 
pid_file "~/.mpd/pid"

# persistent sessions
state_file "~/.mpd/state"
restore_paused "yes"

# audio output
audio_output {
    type "pulse"
    name "PipeWire"
}

# fifo for cava visualizer (rmpc)
audio_output {
    type "fifo"
    name "Visualizer"
    path "/tmp/mpd.fifo"
    format "44100:16:2"
}
