# melange theme for kitty (with some modifications by me)
foreground #ECE1D7
background #292522
background_opacity   0.94

selection_background    #403A36
selection_foreground    #ECE1D7

cursor            #F2A65A
cursor_text_color #17100B

url_color  #7F91B2

bell_border_color     #C0392B

active_border_color   #E08A3C
inactive_border_color #3A2417

tab_bar_background      #34302C
active_tab_background   #34302C
active_tab_foreground   #E49B5D
inactive_tab_background #34302C
inactive_tab_foreground #ECE1D7

color0  #34302C
color1  #BD8183
color2  #78997A
color3  #E49B5D
color4  #7F91B2
color5  #B380B0
color6  #7B9695
color7  #C1A78E
color8  #867462
color9  #D47766
color10 #85B695
color11 #EBC06D
color12 #A3A9CE
color13 #CF9BC2
color14 #89B3B6
color15 #ECE1D7
