# @Per-app effects

# kitty terminal
for_window [app_id="kitty"] opacity 0.75, blur enable
for_window [app_id="zen"] opacity 0.75, blur enable

# actualizaciones (floating)
for_window [app_id="floating_update"] floating enable, resize set 900 600, opacity 0.75, blur enable

# @Per-layer effects
layer_effects "mako" blur enable; corner_radius 8
